version: '3'

services:
  image:
    container_name: hyperf-opentelemetry-image
    image: hyperf-opentelemetry
    command: list
    build: .

  composer:
    container_name: hyperf-opentelemetry-composer
    image: hyperf-opentelemetry
    entrypoint: composer
    volumes:
      - ./:/usr/local/src/

  hyperf-opentelemetry:
    container_name: laravel-otel-commons
    image: hyperf-opentelemetry
    entrypoint: sh
    tty: true
    volumes:
      - ./:/usr/local/src/